name: Build and Package Wheel for Windows

on:
  push:
    branches:
      - tool-development

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install numpy before build
      run: |
        python -m pip install --upgrade pip
        pip install numpy

    - name: Install other dependencies
      run: |
        pip install setuptools wheel

    - name: Build the wheel
      run: |
        python -m build

    - name: Upload the wheel as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl

